name: 'Flutter Test'
on:
  pull_request:
jobs:
  build-test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2     # checkout the repo
      - uses: dorny/test-reporter@v1.5.0        # checkout the repo
        with:
          flutter-version: "3.0.2"
          name: 'flutter name'
      - run: flutter pub get
      - run: flutter test
      - uses: actions/upload-artifact@v2  # upload test results
